version: '3.1'
services:
    postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes:
          - ~/data/postgres/projeto_001_curler:/var/lib/postgresql/data
    redis:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning 
      volumes: 
        - cache:/data
volumes:
  cache:
    driver: local
